// Code generated by hertz generator.

package example

import (
	"context"

	example "gohertz/biz/model/hello/example"

	"github.com/cloudwego/hertz/pkg/app"
)

// HelloWorld .
// @router /hello [GET]
func HelloWorld(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(example.HelloResp)

	resp.RespBody = "hello," + req.Name

	c.JSON(200, resp)
}

// OtherMethod .
// @router /other [POST]
func OtherMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.OtherReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(400, err.Error())
		return
	}

	resp := new(example.OtherResp)

	resp.Resp = "Other method: " + req.Other

	c.JSON(200, resp)
}
